name: F1 Predictor Pipeline

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache FastF1 data
        uses: actions/cache@v3
        with:
          path: ~/.cache/fastf1
          key: ${{ runner.os }}-fastf1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-fastf1-

      - name: Install Git LFS
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install git-lfs
          git lfs install

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- NEW STEP: Sync with remote before running pipeline ---
      - name: Sync with Remote Repository
        run: |
          # Pull LFS files first to ensure they are available locally
          git lfs pull
          # Pull any other changes from the remote branch
          git pull

      - name: Run the update pipeline
        run: |
          echo "Running the main Python pipeline..."
          python run_pipeline.py

      - name: Commit and push updated data and models
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add -A
          # Check if there are any changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Automated data and model update"
            git push
          else
            echo "No changes to commit."
          fi

